project_id = "fnaubekrieovnevstbmb"

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = true

[functions.get-daily-picks]
verify_jwt = true
